config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parents
  # get 'home/index'
  get 'home/about'
  #root 'home#index' this is our home page and the route is pointing at it
  root 'parents#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parent.rb
#this states the the parent belongs to a user in our case is the teahcer who will have login rights
class Parent < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  #this associates the parents with the user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :parents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  #this is our about page where we can put some details on the page we can do any program we want ot go to this page
  # we need to put an instance @about we then go to the about page and put the embedded ruby in <%%>
  def about
    @about_me = "FG Childcare is an after-school and preschool facility located in Swords Co. Dublin"

  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /parents or /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1 or /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    #@parent = Parent.new
    @parent = current_user.parents.build
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents or /parents.json
  def create
    #@parent = Parent.new(parent_params)
    @parent = current_user.parents.build(parent_params)
    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: "Parent was successfully created." }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1 or /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: "Parent was successfully updated." }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1 or /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: "Parent was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  #this makes sure the the correct user is logged in to do a modification on the parent and sends a message if the incorrect user is logged in
  def correct_user
  @parent = current_user.parents.find_by(id: params[:id])
  redirect_to parents_path, notice: "Sorry but you cannot edit this parent as you are not authorised" if @parent.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parent_params
      params.require(:parent).permit(:first_name, :last_name, :email, :phone, :childs_first_name, :childs_last_name, :childs_dob, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/home/_header.html.erb
<!-- this give the navbar a color of blue and wrtiting white-->
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <!-- this links to the root path and we need to give it a class this is the ancor task this will bring us back to our home page when we click on it -->
  <%= link_to 'FG Childcare', root_path, class:"navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <!--the home about path in our home controller which is in ur routes on config -->
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
<!--This is telling me if the user is signed in they can do the below taks  -->
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add a Parent', new_parent_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'edit profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <% else  %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class:"nav-link" %>
        </li>
          <% end %>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us </h1>
<!-- the = sign prints it to the page -->
<p>
  <%= @about_me %>
</p>

app/views/home/index.html.erb
<!--This is our index page and if we want to change anything we just type it in -->
<h1>Welcome to FG Childcare database</h1>
You can now access FG Childcare by signing up and signing in.

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;
    </span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <title>CaProject</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS  was installed and this is the link this was copied from bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

  <title>FG Childcare</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<!--this is where we put the tag to render the partial onto the screen we are using the render tag <%%> %> -->
  <%= render 'home/header' %>
  <div class="container">
    <br/>
    <!--This tells me if there is an alert to do something
    <% if notice %>
      <%= render "layouts/alerts" %>
      <% end %>
    <br/>
    <!- once inside the yield tag the information will be sent to the relevent pages -->
  <%= yield %>
  </div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
  <!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
-->
</body>
</html>

app/views/parents/_form.html.erb
<!--this is where are forms are stored for the pages -->
<%= form_with(model: parent) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
        <% parent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name"%>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email Address" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone No" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :childs_first_name, class:"form-control", placeholder:"Child's First Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :childs_last_name, class:"form-control", placeholder:"Child's Last Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :childs_dob, class:"form-control", placeholder:"Child's DOB" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :parent_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

<br/>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>
<br/>
<%= render 'form', parent: @parent %>
<br/>

<%= link_to 'Show', @parent, class:"btn btn-info" %>
<%= link_to 'Remove', @parent, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-info"  %>
<%= link_to 'Back', parents_path, class:"btn btn-info" %>

app/views/parents/index.html.erb
<% if user_signed_in? %>
<!-- We used bootstrap to design our table to look nicer on the pages instead of having just the plain table-->
<!-- We used bootstrap to make the froms and tables look nicer with some design elements jumbotron a square box surround was used and rows where as we scroll over the lines it changes color-->
  <table class="table table-striped table-hover table-bordered">
    <thead class='table-info'>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Childs first name</th>
        <th>Childs last name</th>
        <th>Childs dob</th>
        <th>User Id</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @parents.each do |parent| %>
        <% if parent.user == current_user %>
        <tr>
          <td>
              <%= link_to parent.first_name + ' ' +  parent.last_name, parent %>
          </td>
          <td><%= parent.email %></td>
          <td><%= parent.phone %></td>
          <td><%= parent.childs_first_name %></td>
          <td><%= parent.childs_last_name %></td>
          <td><%= parent.childs_dob %></td>
          <td><%= parent.user_id %></td>
          <td><%= link_to 'Remove', parent, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-info btn-sm"  %></td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>
<!--This give a line break as the buttons where on top of each other -->
<br>
<!--The buttons where styled using bootstrap to make them stand out nicer-->
  <%= link_to 'New Parent', new_parent_path, class:"btn btn-primary"  %>
<% else %>

  <h1>Welcome to FG Childcare</h1>
  You can now access FG Childcare Services by signing up
<% end %>

app/views/parents/new.html.erb
<h1>Add new parent</h1>
<br/>

<%= render 'form', parent: @parent %>
<br/>

<%= link_to 'Back', parents_path, class:"btn btn-primary" %>

app/views/parents/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
  <h1 class="display-4">
    <%= @parent.first_name %>
    <%= @parent.last_name %>

  </h1>
  <p class="lead">
    <%= @parent.email %>|
    <%= @parent.phone %>
  </p>

  <hr class="my-4">
  <h1>Childs Details</h1>
  <p>
    <%= @parent.childs_first_name %>
    <%= @parent.childs_last_name %> |
    <%= @parent.childs_dob %>
   </p>
  <br/>

  <%= link_to 'Edit', edit_parent_path(@parent), class:"btn btn-primary" %>
  <%= link_to 'Back', parents_path, class:"btn btn-info" %>

  </div>
</div>